version: '3'
services:
  app:
    build: .
    ports:
     - "5000:80"
    volumes:
     - .:/project
    depends_on:
     - postgres
    environment:
      - ENV=DOCKER

  postgres:
    image: "postgres:11.1"
    ports:
      - "5432:5432"